z_os: >-
  {{
    {
      'Darwin': 'darwin',
      'Debian': 'linux',
      'Windows': 'windows'
    }[ansible_os_family] | default('')
  }}
z_arch: >-
  {{
    {
      'x86_64': 'amd64',
      'aarch64': 'arm64',
      'i386': '386'
    }[ansible_architecture] | default('')
  }}

rep_table:
  shard-a.zygote.run:
    rep-index: 0
    shard-index: 0
  shard-b.zygote.run:
    rep-index: 1
    shard-index: 0
  shard-c.zygote.run:
    rep-index: 2
    shard-index: 0
  shard-a-1.zygote.run:
    rep-index: 0
    shard-index: 1
  shard-b-1.zygote.run:
    rep-index: 1
    shard-index: 1
  shard-c-1.zygote.run:
    rep-index: 2
    shard-index: 1
  shard-a-2.zygote.run:
    rep-index: 0
    shard-index: 2
  shard-b-2.zygote.run:
    rep-index: 1
    shard-index: 2
  shard-c-2.zygote.run:
    rep-index: 2
    shard-index: 2

ansible_ssh_user: root
