---
- name: Copy CA certificate to remote machines
  copy:
    src: '{{ lookup("env", "HOME") }}/.config/zygote/certs/ca/ca_cert.pem'
    dest: '{{ zygote_home }}/certs/ca/ca_cert.pem'
    owner: zygote
    group: zygote
    mode: "0600"
  become: true

- name: Remove ca_key.pem
  file:
    path: '{{ zygote_home }}/certs/ca/ca_key.pem'
    state: absent

- name: Deploy function certificates
  copy:
    src: '{{ lookup("env", "HOME") }}/.config/zygote/certs/functions/{{ inventory_hostname }}'
    dest: '{{ zygote_home }}/certs/functions/'
    owner: zygote
    group: zygote
    mode: "0600"
  become: true
