version: "3.9"

services:
  gitlab-runner:
    image: docker.io/gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: unless-stopped
    volumes:
      - /mnt/z/volumes/${TENANT}/${POD}/gitlab-runner_config:/etc/gitlab-runner
      - /var/run/podman/podman.sock:/var/run/docker.sock
    networks:
      - ${TENANT}_${POD}_gitlab-runner_net

networks:
  ${TENANT}_${POD}_gitlab-runner_net:
    driver: bridge
