---
- name: Create zygote base directory
  file:
    path: /var/lib/zygote
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Create certs directory
  file:
    path: /var/lib/zygote/certs
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Create ca directory
  file:
    path: /var/lib/zygote/certs/ca
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Create functions directory
  file:
    path: /var/lib/zygote/certs/functions
    state: directory
    mode: "0755" # Restrictive permissions for functions directory
    owner: root
    group: root
