hosts:
  default:
    - name: controller_1
      ansible_host: 49.13.202.136
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
      groups:
        - controller
    - name: main_1
      ansible_host: 116.203.68.173
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
      groups:
        - main 
    - name: main_2
      ansible_host: 188.245.180.49
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
      groups:
        - main
  main:
    - name: controller_1
      ansible_host: 195.201.20.94
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
      groups:
        - controller
    - name: main_1
      ansible_host: 162.55.209.109
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
      groups:
        - main 
    - name: main_2
      ansible_host: 116.203.45.160
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
      groups:
        - main
