version: "3.9"

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
    ports:
      - "127.0.0.1:${PORT:-3004}:8080"
    volumes:
      - /mnt/z/volumes/${TENANT}/${POD}/open-webui_data:/app/backend/data
    networks:
      - ${TENANT}_${POD}_open-webui_net

  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: open-webui_ollama
    restart: unless-stopped
    volumes:
      - /mnt/z/volumes/${TENANT}/${POD}/ollama_data:/root/.ollama
    networks:
      - ${TENANT}_${POD}_open-webui_net

networks:
  ${TENANT}_${POD}_open-webui_net:
    driver: bridge
