---
- name: Install binaries
  include_role:
    name: z_install
  vars:
    func_name: zygote
    z_binaries:
      - path: "{{ zcore_binary_file }}"
        url: "{{ zcore_url }}"
        privileged_ports: true

- name: Add Systemd service
  include_role:
    name: z_service
  vars:
    func_name: zygote
    func_home: /var/lib/zygote
    func_bin_file: /usr/local/bin/zcore
