version: "3.9"

services:
  redis:
    image: docker.io/redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:${PORT:-6379}:6379"
    volumes:
      - /mnt/z/volumes/${TENANT}/${POD}/redis_data:/data
    networks:
      - ${TENANT}_${POD}_redis_net

networks:
  ${TENANT}_${POD}_redis_net:
    driver: bridge
