version: "3.9"

services:
  alertmanager:
    image: docker.io/prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - "127.0.0.1:${PORT:-9093}:9093"
    volumes:
      - /mnt/z/volumes/${TENANT}/${POD}/alertmanager_data:/alertmanager
      - /mnt/z/volumes/${TENANT}/${POD}/alertmanager_config:/etc/alertmanager
    networks:
      - ${TENANT}_${POD}_alertmanager_net

networks:
  ${TENANT}_${POD}_alertmanager_net:
    driver: bridge
