---
- name: Ensure service user exists
  user:
    name: "{{ z_service_user }}"
    system: yes
    create_home: "{{ z_service_create_home }}"
    home: "{{ z_service_home_dir if z_service_create_home else omit }}"
    shell: /sbin/nologin
  become: yes

- name: Ensure service group exists
  group:
    name: "{{ z_service_group }}"
    system: yes
  become: yes

- name: Check if service binary exists
  stat:
    path: "{{ z_service_binary_path }}"
  register: binary_stat
  failed_when: not binary_stat.stat.exists

- name: Set CAP_NET_BIND_SERVICE capability on binary
  command: setcap 'cap_net_bind_service=+ep' {{ z_service_binary_path }}
  become: true

- name: Ensure working directory exists if specified
  file:
    path: "{{ z_service_working_dir }}"
    state: directory
    owner: "{{ z_service_user }}"
    group: "{{ z_service_group }}"
    mode: '0755'
  when: z_service_working_dir != ""
  become: yes

- name: Deploy service file
  template:
    src: z_service.j2
    dest: "/etc/systemd/system/{{ z_service_name }}.service"
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Ensure service is enabled and in desired state
  systemd:
    name: "{{ z_service_name }}"
    state: "{{ z_service_state }}"
    enabled: "{{ z_service_enabled }}"
  become: yes

- name: Sign service accounts
  command: "z cert sign --name {{ z_service_domain }}"
  args:
    creates: "{{ z_service_cert_file }}"
  environment:
    ZYGOTE_CONFIG_HOME: "{{ z_service_working_dir }}"

- name: Recursively set ownership of cert_dir to service user
  ansible.builtin.file:
    path: "{{ z_service_cert_dir }}"
    owner: "{{ z_service_user }}"
    group: "{{ z_service_group }}"
    state: directory
    recurse: true   # Recursively apply ownership to all contents
  become: true

- name: Fix cert_dir permissions
  file:
    path: "/var/lib/zygote/certs/functions/{{ inventory_hostname }}"
    state: directory
    mode: 0700
    owner: zygote
    group: zygote
  become: true

- name: Fix function dir permissions
  file:
    path: "/var/lib/zygote/certs/functions"
    state: directory
    mode: 0755
    owner: root
    group: root
  become: true

- name: Reload systemd
  command: systemctl daemon-reload
  become: yes

- name: Restart z_service
  systemd:
    name: "{{ z_service_name }}"
    state: restarted
  become: yes
