version: "3.9"

services:
  pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: changeme
    ports:
      - "127.0.0.1:${PORT:-5050}:80"
    volumes:
      - /mnt/z/volumes/${TENANT}/${POD}/pgadmin_data:/var/lib/pgadmin
    networks:
      - ${TENANT}_${POD}_pgadmin_net

networks:
  ${TENANT}_${POD}_pgadmin_net:
    driver: bridge
