#!/usr/bin/env bash

if [[ $# -eq 0 ]]; then
  echo "Usage: $0 <deployment> [up|down|restart|logs]"
  exit 1
fi

backup() {
  source .env
  podman-compose -f podman-compose.yaml pause
  sudo tar -czf "pod_backup.tar.gz" -C "/mnt/z/volumes/$TENANT/$POD" .
  podman-compose -f podman-compose.yaml unpause
}

restore() {
  podman-compose -f podman-compose.yaml down -v
  source .env
  sudo rm -rf "/mnt/z/volumes/$TENANT/$POD"
  make_volume
  sudo tar -xpzf "pod_backup.tar.gz" -C "/mnt/z/volumes/$TENANT/$POD"
  podman-compose -f podman-compose.yaml up -d
}

make_volume(){
  source .env
  sudo mkdir -p "/mnt/z/volumes/$TENANT/$POD"
  sudo chown -R $USER:$USER "/mnt/z/volumes/$TENANT/$POD"
  mkdir -p "/mnt/z/volumes/$TENANT/$POD/rabbitmq_data"
}

DEPLOYMENT="rabbitmq"

cd $HOME/src/github.com/platforge-cloud/$DEPLOYMENT

while [[ $# -gt 0 ]]; do
  case "$1" in
    up)
      make_volume
      podman-compose -f podman-compose.yaml up -d
      shift
      ;;
    down)
      podman-compose -f podman-compose.yaml down -v
      shift
      ;;
    destroy)
      podman-compose -f podman-compose.yaml down -v
      source .env
      sudo rm -rf "/mnt/z/volumes/$TENANT/$POD/rabbitmq_data"
      shift
      ;;
    restart|logs)
      podman-compose -f podman-compose.yaml $1
      shift
      ;;
    backup)
      backup
      shift
      ;;
    restore)
      restore
      shift
      ;;
    *)
      DEPLOYMENT="$1"
      cd $HOME/src/github.com/platforge-cloud/$DEPLOYMENT
      shift
      ;;
  esac
done
