---
- name: "Check"
  tags:
    - check
    - z
  shell: |
    ./scripts/check
  args:
    chdir: "{{ workspace }}"

- name: "Build"
  tags:
   - build
  shell: |
    ./scripts/build
  args:
    chdir: "{{ workspace }}"

- name: "Smoke"
  tags:
   - smoke
  shell: |
    ./scripts/smoke
  args:
    chdir: "{{ workspace }}"
