version: "3.9"

services:
  haproxy:
    image: docker.io/haproxy:latest
    container_name: haproxy
    restart: unless-stopped
    ports:
      - "127.0.0.1:${PORT:-8080}:80"
      - "127.0.0.1:8404:8404"
    volumes:
      - /mnt/z/volumes/${TENANT}/${POD}/haproxy_config:/usr/local/etc/haproxy
    networks:
      - ${TENANT}_${POD}_haproxy_net

networks:
  ${TENANT}_${POD}_haproxy_net:
    driver: bridge
