version: "3.9"

services:
  hbbs:
    image: docker.io/rustdesk/rustdesk-server:latest
    container_name: rustdesk_hbbs
    restart: unless-stopped
    command: hbbs
    ports:
      - "127.0.0.1:${PORT:-21115}:21115"
      - "127.0.0.1:21116:21116"
      - "127.0.0.1:21116:21116/udp"
      - "127.0.0.1:21118:21118"
    volumes:
      - /mnt/z/volumes/${TENANT}/${POD}/rustdesk_data:/root
    networks:
      - ${TENANT}_${POD}_rustdesk_net

  hbbr:
    image: docker.io/rustdesk/rustdesk-server:latest
    container_name: rustdesk_hbbr
    restart: unless-stopped
    command: hbbr
    ports:
      - "127.0.0.1:21117:21117"
      - "127.0.0.1:21119:21119"
    volumes:
      - /mnt/z/volumes/${TENANT}/${POD}/rustdesk_data:/root
    networks:
      - ${TENANT}_${POD}_rustdesk_net

networks:
  ${TENANT}_${POD}_rustdesk_net:
    driver: bridge
