version: "3.9"

services:
  caddy:
    image: docker.io/library/caddy:2
    container_name: ${TENANT}_${NAMESPACE}_${POD}_caddy
    restart: unless-stopped
    ports:
      - "127.0.0.1:${PORT}:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /mnt/z/volumes/${TENANT}/${NAMESPACE}/${POD}/caddy_sites:/etc/caddy/sites:ro
      - /mnt/z/volumes/${TENANT}/${NAMESPACE}/${POD}/caddy_data:/data
      - /mnt/z/volumes/${TENANT}/${NAMESPACE}/${POD}/caddy_config:/config
    networks:
      - z-${TENANT}-${NAMESPACE}-${POD}
      - z-${TENANT}

networks:
  z-${TENANT}-${NAMESPACE}-${POD}:
    external: true
  z-${TENANT}:
    external: true
