---
- name: Create zygote_user
  user:
    name: "{{ zygote_user }}"
    comment: "Zygote user"
    system: true
    shell: /usr/sbin/nologin
    createhome: false
    state: present

- name: Create CA directory
  become: true
  file:
    state: directory
    path: "{{ zygote_ca_cert_dir }}"
    owner: "{{ zygote_user }}"
    group: "{{ zygote_user }}"
    mode: 0755
