version: "3.9"

services:
  loki:
    image: docker.io/grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - "127.0.0.1:${PORT:-3100}:3100"
    volumes:
      - /mnt/z/volumes/${TENANT}/${POD}/loki_data:/loki
    networks:
      - ${TENANT}_${POD}_loki_net

networks:
  ${TENANT}_${POD}_loki_net:
    driver: bridge
