---
- file:
    state: directory
    path: "{{ zygote_ca_cert_dir }}"
    owner: root
    group: root
    mode: 0755

- name: Copy CA cert to destination
  become: true
  copy:
    src: "{{ zygote_ca_cert_file }}"
    dest: "{{ zygote_ca_cert_file }}"
    owner: root
    mode: 0755
