---
- name: Push Play
  hosts: localhost
  gather_facts: false
  roles:
    - z_build
    - z_tag_release
    - z_add_shards

- name: Deploy
  hosts: shards
  gather_facts: false
  roles:
    - role: z_join
    - role: z_service
      vars:
        z_service_name: "zcore"
  tags:
    - z_deploy
    - never
