---
- name: Main Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Run check.sh"
      shell: |
        ./playbooks/files/check.sh
        ./playbooks/files/build.sh
      args:
        chdir: "{{ workspace }}"
  vars_files:
    - vars/main.yaml

- name: Setup the controller VM
  hosts: controller
  gather_facts: true
  become: true
  roles:
    - zygote_controller
  vars_files:
    - vars/main.yaml
  tags:
    - controller
