---
- name: Push Play
  hosts: localhost
  gather_facts: false
  roles:
    - z_build
    - z_dist
    - z_add_shards
  vars: 
    z_domain: zygote.run
  tags: always

- name: Deploy
  hosts: shards
  gather_facts: false
  roles:
    - z_deploy
  tags: z_deploy
