---
- name: Build
  hosts: localhost
  gather_facts: false
  collections:
    - evgnomon.catamaran
  roles:
    - z_build

- name: Release on tag
  hosts: localhost
  gather_facts: false
  collections:
    - evgnomon.catamaran
  roles:
    - z_tag_release

- name: Add shards to inventory
  hosts: localhost
  gather_facts: false
  collections:
    - evgnomon.catamaran
  roles:
    - z_add_shards
  tags:
    - z_deploy
    - never

- name: Add front
  hosts: localhost
  collections:
    - evgnomon.catamaran
  tasks:
    - name: Add front
      add_host:
        name: "{{ item }}"
        groups: front
        ansible_user: "root"
      with_items:
        - front-a-1.zygote.run
        - front-b-1.zygote.run
  tags:
    - z_deploy
    - never

- name: Deploy ZCore on shards
  hosts:
    - shards
  gather_facts: false
  collections:
    - evgnomon.catamaran
  roles:
    - role: z_service
      vars:
        z_service_name: "zcore"
  tags:
    - z_deploy
    - never

- name: Deploy ZCore on front
  hosts:
    - front
  gather_facts: false
  collections:
    - evgnomon.catamaran
  roles:
    - role: z_service
      vars:
        z_service_name: "zcore"
        z_use_domain_cert: true
  tags:
    - z_deploy
    - never

- name: Join Shards
  hosts: shards
  gather_facts: false
  collections:
    - evgnomon.catamaran
  roles:
    - role: z_join
  tags:
    - z_join
    - never
