---
- file:
   state: directory
   path: "{{ func_cert_dir }}"
   recurse: true
   owner: "{{ func_name }}"
   group: "{{ func_name }}"
   mode: 0700

- name: Copy files from source to destination
  become: true
  copy:
    src: "{{ func_cert_dir }}"
    dest: "{{ func_cert_dir }}"
    owner: "{{ func_name }}"
    mode: 0700
