name: Release Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/evgnomon/ark:main
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Run tests
      run: go test ./...
    
    - name: Build binary
      run: |
        go build -buildvcs=false -o clapp ./cmd/zygote
    
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ github.ref }} zygote --title "Release ${{ github.ref }}" --notes "Release ${{ github.ref }}" --target ${{ github.sha }}
