name: Yacht

on:
  push:
    branches:
      - '*'
    tags:
      - "*"
  delete:
    branches:
      - '*'
      - '!main'

jobs:
  yacht:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/evgnomon/barge:main
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v5
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Run Playbook
      uses: evgnomon/yacht@main
      with:
        vault: ${{ secrets.VAULT_FILE }}
        vault_pass: ${{ secrets.VAULT_PASS }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        inventory: playbooks/${{ steps.extract_branch.outputs.branch }}_inventory.yaml
